{{- if and (.Values.secret.create) (.Values.secret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default "cloud-config" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
{{- if .Values.secret.data }}
stringData:
  {{ .Values.secret.data | toYaml | trimSuffix "\n" | nindent 2 }}
{{- else }}
data:
  {{ if .Values.cloudConfigContents -}}
  cloud.conf: |
    {{ .Values.cloudConfigContents | b64enc }}
  {{ else -}}
  cloud.conf: {{ include "cloudConfig" . | b64enc }}
  {{ end -}}
{{- end }}
{{- end }}
